/*

undefined
Customer Selection for Configurator v2

!!! AUTO GENERATED BY IOTSFJS REFRAIN FROM MANUAL EDITING !!!
See https://www.npmjs.com/package/io-ts-from-json-schema

*/

import * as t from 'io-ts';
import * as CustomerSelectionCommon_ from './customerSelectionCommon';

export const schemaId = 'http://maasglobal.com/core/components/customerSelectionV2.json';

// CustomerSelectionV2
// The default export. More information at the top.
export type CustomerSelectionV2 = t.Branded<
  Record<string, CustomerSelectionCommon_.ConfigChoiceSelection>,
  CustomerSelectionV2Brand
>;
export type CustomerSelectionV2C = t.BrandC<
  t.RecordC<t.StringC, typeof CustomerSelectionCommon_.ConfigChoiceSelection>,
  CustomerSelectionV2Brand
>;
export const CustomerSelectionV2: CustomerSelectionV2C = t.brand(
  t.record(t.string, CustomerSelectionCommon_.ConfigChoiceSelection),
  (
    x,
  ): x is t.Branded<
    Record<string, CustomerSelectionCommon_.ConfigChoiceSelection>,
    CustomerSelectionV2Brand
  > => true,
  'CustomerSelectionV2',
);
export interface CustomerSelectionV2Brand {
  readonly CustomerSelectionV2: unique symbol;
}

export default CustomerSelectionV2;

// Success
