/*

undefined
MaaS personal data validation rules

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';

export const schemaId =
  'http://maasglobal.com/core/components/personalDataValidation.json';

// PersonalDataValidation
// The default export. More information at the top.
export type PersonalDataValidation = t.Branded<
  {
    type?: 'value' | 'enum' | 'length' | 'regex' | 'date' | 'dateDurationTillNow';
    operator?: '>' | '>=' | '<' | '<=' | '=' | '!=';
    config?: {
      value?: string | number | boolean;
      meta?: {};
    };
    errorCode?: string;
  },
  PersonalDataValidationBrand
>;
export const PersonalDataValidation = t.brand(
  t.partial({
    type: t.union([
      t.literal('value'),
      t.literal('enum'),
      t.literal('length'),
      t.literal('regex'),
      t.literal('date'),
      t.literal('dateDurationTillNow'),
    ]),
    operator: t.union([
      t.literal('>'),
      t.literal('>='),
      t.literal('<'),
      t.literal('<='),
      t.literal('='),
      t.literal('!='),
    ]),
    config: t.partial({
      value: t.union([t.string, t.number, t.boolean]),
      meta: t.type({}),
    }),
    errorCode: t.string,
  }),
  (
    x,
  ): x is t.Branded<
    {
      type?: 'value' | 'enum' | 'length' | 'regex' | 'date' | 'dateDurationTillNow';
      operator?: '>' | '>=' | '<' | '<=' | '=' | '!=';
      config?: {
        value?: string | number | boolean;
        meta?: {};
      };
      errorCode?: string;
    },
    PersonalDataValidationBrand
  > => true,
  'PersonalDataValidation',
);
export interface PersonalDataValidationBrand {
  readonly PersonalDataValidation: unique symbol;
}

export default PersonalDataValidation;

// Success
