/*

undefined
A spaceDemand describes nr of passengers (adults, infatnts, etc) and bags (luggages).

!!! AUTO GENERATED BY IOTSFJS REFRAIN FROM MANUAL EDITING !!!
See https://www.npmjs.com/package/io-ts-from-json-schema

*/

import * as t from 'io-ts';

export const schemaId = 'http://maasglobal.com/core/components/spaceDemand.json';

// SpaceDemand
// The default export. More information at the top.
export type SpaceDemand = t.Branded<
  {
    adults?: number;
    children?: number;
    infants?: number;
    bags?: number;
  } & Record<string, unknown>,
  SpaceDemandBrand
>;
export type SpaceDemandC = t.BrandC<
  t.IntersectionC<
    [
      t.PartialC<{
        adults: t.NumberC;
        children: t.NumberC;
        infants: t.NumberC;
        bags: t.NumberC;
      }>,
      t.RecordC<t.StringC, t.UnknownC>,
    ]
  >,
  SpaceDemandBrand
>;
export const SpaceDemand: SpaceDemandC = t.brand(
  t.intersection([
    t.partial({
      adults: t.number,
      children: t.number,
      infants: t.number,
      bags: t.number,
    }),
    t.record(t.string, t.unknown),
  ]),
  (
    x,
  ): x is t.Branded<
    {
      adults?: number;
      children?: number;
      infants?: number;
      bags?: number;
    } & Record<string, unknown>,
    SpaceDemandBrand
  > => true,
  'SpaceDemand',
);
export interface SpaceDemandBrand {
  readonly SpaceDemand: unique symbol;
}

export default SpaceDemand;

// Success
