/*

undefined
Request schema for update a state of a specific booking with a TSP ID from a TSP adapter

!!! AUTO GENERATED BY IOTSFJS REFRAIN FROM MANUAL EDITING !!!
See https://www.npmjs.com/package/io-ts-from-json-schema

*/

import * as t from 'io-ts';

import * as Booking_4353_ from '../../core/booking';
import * as BookingMeta_c057_ from '../../core/booking-meta';
import * as Configurator_2e96_ from '../../core/components/configurator';
import * as CustomerSelection_57c3_ from '../../core/components/customerSelection';

export type Defined = {} | null;
export class DefinedType extends t.Type<Defined> {
  readonly _tag: 'DefinedType' = 'DefinedType';
  constructor() {
    super(
      'defined',
      (u): u is Defined => typeof u !== 'undefined',
      (u, c) => (this.is(u) ? t.success(u) : t.failure(u, c)),
      t.identity,
    );
  }
}
export type DefinedC = {} & DefinedType;
export const Defined: DefinedC = new DefinedType();

export const schemaId = 'https://schemas.maas.global/tsp/booking-update/request.json';

// Request
// The default export. More information at the top.
export type Request = t.Branded<
  ({
    tspId?: Booking_4353_.TspId;
    state?: 'RESERVED' | 'ACTIVATED' | 'ON_HOLD' | 'EXPIRED' | 'FINISHED';
    configurator?: Configurator_2e96_.Configurator;
    meta?: BookingMeta_c057_.BookingMeta;
    terms?: Booking_4353_.Terms;
    customerSelection?: CustomerSelection_57c3_.CustomerSelection;
  } & Record<string, unknown>) & {
    tspId: Defined;
  },
  RequestBrand
>;
export type RequestC = t.BrandC<
  t.IntersectionC<
    [
      t.IntersectionC<
        [
          t.PartialC<{
            tspId: typeof Booking_4353_.TspId;
            state: t.UnionC<
              [
                t.LiteralC<'RESERVED'>,
                t.LiteralC<'ACTIVATED'>,
                t.LiteralC<'ON_HOLD'>,
                t.LiteralC<'EXPIRED'>,
                t.LiteralC<'FINISHED'>,
              ]
            >;
            configurator: typeof Configurator_2e96_.Configurator;
            meta: typeof BookingMeta_c057_.BookingMeta;
            terms: typeof Booking_4353_.Terms;
            customerSelection: typeof CustomerSelection_57c3_.CustomerSelection;
          }>,
          t.RecordC<t.StringC, t.UnknownC>,
        ]
      >,
      t.TypeC<{
        tspId: typeof Defined;
      }>,
    ]
  >,
  RequestBrand
>;
export const Request: RequestC = t.brand(
  t.intersection([
    t.intersection([
      t.partial({
        tspId: Booking_4353_.TspId,
        state: t.union([
          t.literal('RESERVED'),
          t.literal('ACTIVATED'),
          t.literal('ON_HOLD'),
          t.literal('EXPIRED'),
          t.literal('FINISHED'),
        ]),
        configurator: Configurator_2e96_.Configurator,
        meta: BookingMeta_c057_.BookingMeta,
        terms: Booking_4353_.Terms,
        customerSelection: CustomerSelection_57c3_.CustomerSelection,
      }),
      t.record(t.string, t.unknown),
    ]),
    t.type({
      tspId: Defined,
    }),
  ]),
  (
    x,
  ): x is t.Branded<
    ({
      tspId?: Booking_4353_.TspId;
      state?: 'RESERVED' | 'ACTIVATED' | 'ON_HOLD' | 'EXPIRED' | 'FINISHED';
      configurator?: Configurator_2e96_.Configurator;
      meta?: BookingMeta_c057_.BookingMeta;
      terms?: Booking_4353_.Terms;
      customerSelection?: CustomerSelection_57c3_.CustomerSelection;
    } & Record<string, unknown>) & {
      tspId: Defined;
    },
    RequestBrand
  > => true,
  'Request',
);
export type RequestBrand = {
  readonly Request: unique symbol;
};

export default Request;

// Success
