/*

undefined
Insert a pending verification personal document object

!!! AUTO GENERATED BY IOTSFJS REFRAIN FROM MANUAL EDITING !!!
See https://www.npmjs.com/package/io-ts-from-json-schema

*/

import * as t from 'io-ts';
import * as PersonalDocument_ from '../../../../core/personal-document';

export type Defined = {} | null;
export class DefinedType extends t.Type<Defined> {
  readonly _tag: 'DefinedType' = 'DefinedType';
  constructor() {
    super(
      'defined',
      (u): u is Defined => typeof u !== 'undefined',
      (u, c) => (this.is(u) ? t.success(u) : t.failure(u, c)),
      t.identity,
    );
  }
}
export interface DefinedC extends DefinedType {}
export const Defined: DefinedC = new DefinedType();

export const schemaId =
  'http://maasglobal.com/maas-backend/customers/personal-documents/create/response.json';

// Response
// The default export. More information at the top.
export type Response = t.Branded<
  {
    type?: PersonalDocument_.DocumentType;
    status?: PersonalDocument_.DocumentStatus;
  } & {
    type: Defined;
    status: Defined;
  },
  ResponseBrand
>;
export type ResponseC = t.BrandC<
  t.IntersectionC<
    [
      t.PartialC<{
        type: typeof PersonalDocument_.DocumentType;
        status: typeof PersonalDocument_.DocumentStatus;
      }>,
      t.TypeC<{
        type: typeof Defined;
        status: typeof Defined;
      }>,
    ]
  >,
  ResponseBrand
>;
export const Response: ResponseC = t.brand(
  t.intersection([
    t.partial({
      type: PersonalDocument_.DocumentType,
      status: PersonalDocument_.DocumentStatus,
    }),
    t.type({
      type: Defined,
      status: Defined,
    }),
  ]),
  (
    x,
  ): x is t.Branded<
    {
      type?: PersonalDocument_.DocumentType;
      status?: PersonalDocument_.DocumentStatus;
    } & {
      type: Defined;
      status: Defined;
    },
    ResponseBrand
  > => true,
  'Response',
);
export interface ResponseBrand {
  readonly Response: unique symbol;
}

export default Response;

// Success
