/*

undefined
Schema for MODE_GONDOLA meta field

!!! AUTO GENERATED BY IOTSFJS REFRAIN FROM MANUAL EDITING !!!
See https://www.npmjs.com/package/io-ts-from-json-schema

*/

import * as t from 'io-ts';

export const schemaId = 'http://maasglobal.com/core/modes/MODE_GONDOLA.json';

// MODE_GONDOLA
// The default export. More information at the top.
export type MODE_GONDOLA = t.Branded<{}, MODE_GONDOLABrand>;
export const MODE_GONDOLA = t.brand(
  t.type({}),
  (x): x is t.Branded<{}, MODE_GONDOLABrand> => true,
  'MODE_GONDOLA',
);
export interface MODE_GONDOLABrand {
  readonly MODE_GONDOLA: unique symbol;
}

export default MODE_GONDOLA;

// Success
