/*

undefined
Request schema for subscriptions-intents-update-state

!!! AUTO GENERATED BY IOTSFJS REFRAIN FROM MANUAL EDITING !!!
See https://www.npmjs.com/package/io-ts-from-json-schema

*/

import * as t from 'io-ts';
import * as Units_ from '../../../core/components/units';
import * as State_ from '../../../core/components/state';
import * as ApiCommon_ from '../../../core/components/api-common';

type Defined =
  | Record<string, unknown>
  | Array<unknown>
  | string
  | boolean
  | number
  | null;
const Defined = t.union([
  t.UnknownRecord,
  t.UnknownArray,
  t.string,
  t.boolean,
  t.number,
  t.null,
]);

export const schemaId =
  'http://maasglobal.com/maas-backend/subscriptions/subscriptions-intents-update-state/request.json';

// Request
// The default export. More information at the top.
export type Request = t.Branded<
  {
    identityId?: Units_.IdentityId;
    userId?: Units_.IdentityId;
    subscriptionIntentId?: Units_.Uuid;
    payload?: {
      state?: State_.SubscriptionIntentState;
    };
    headers?: ApiCommon_.Headers;
  } & {
    identityId: Defined;
    userId: Defined;
    subscriptionIntentId: Defined;
    payload: Defined;
  },
  RequestBrand
>;
export const Request = t.brand(
  t.intersection([
    t.partial({
      identityId: Units_.IdentityId,
      userId: Units_.IdentityId,
      subscriptionIntentId: Units_.Uuid,
      payload: t.partial({
        state: State_.SubscriptionIntentState,
      }),
      headers: ApiCommon_.Headers,
    }),
    t.type({
      identityId: Defined,
      userId: Defined,
      subscriptionIntentId: Defined,
      payload: Defined,
    }),
  ]),
  (
    x,
  ): x is t.Branded<
    {
      identityId?: Units_.IdentityId;
      userId?: Units_.IdentityId;
      subscriptionIntentId?: Units_.Uuid;
      payload?: {
        state?: State_.SubscriptionIntentState;
      };
      headers?: ApiCommon_.Headers;
    } & {
      identityId: Defined;
      userId: Defined;
      subscriptionIntentId: Defined;
      payload: Defined;
    },
    RequestBrand
  > => true,
  'Request',
);
export interface RequestBrand {
  readonly Request: unique symbol;
}

export default Request;

// Success
