/*

undefined
Response schema for estimating a configured product option

!!! AUTO GENERATED BY IOTSFJS REFRAIN FROM MANUAL EDITING !!!
See https://www.npmjs.com/package/io-ts-from-json-schema

*/

import * as t from 'io-ts';
import * as ProductOption_ from '../../core/product-option';

export const schemaId = 'http://maasglobal.com/tsp/estimate/request.json';

// Response
// The default export. More information at the top.
export type Response = t.Branded<
  {
    option?: ProductOption_.ProductOption;
  },
  ResponseBrand
>;
export type ResponseC = t.BrandC<
  t.PartialC<{
    option: typeof ProductOption_.ProductOption;
  }>,
  ResponseBrand
>;
export const Response: ResponseC = t.brand(
  t.partial({
    option: ProductOption_.ProductOption,
  }),
  (
    x,
  ): x is t.Branded<
    {
      option?: ProductOption_.ProductOption;
    },
    ResponseBrand
  > => true,
  'Response',
);
export interface ResponseBrand {
  readonly Response: unique symbol;
}

export default Response;

// Success
