/*

undefined
Save user consent to send all TSP required personal documents to TSP

!!! AUTO GENERATED BY IOTSFJS REFRAIN FROM MANUAL EDITING !!!
See https://www.npmjs.com/package/io-ts-from-json-schema

*/

import * as t from 'io-ts';
import * as Units_ from '../../../../core/components/units';
import * as PersonalDocument_ from '../../../../core/personal-document';

type Defined =
  | Record<string, unknown>
  | Array<unknown>
  | string
  | boolean
  | number
  | null;
const Defined = t.union([
  t.UnknownRecord,
  t.UnknownArray,
  t.string,
  t.boolean,
  t.number,
  t.null,
]);

export const schemaId =
  'http://maasglobal.com/maas-backend/customers/personal-documents/consent/response.json';

// Response
// The default export. More information at the top.
export type Response = t.Branded<
  {
    identityId?: Units_.IdentityId;
    id?: Units_.Uuid;
    partyId?: PersonalDocument_.PartyId;
    partyType?: PersonalDocument_.PartyType;
  } & {
    identityId: Defined;
    id: Defined;
    partyId: Defined;
    partyType: Defined;
  },
  ResponseBrand
>;
export const Response = t.brand(
  t.intersection([
    t.partial({
      identityId: Units_.IdentityId,
      id: Units_.Uuid,
      partyId: PersonalDocument_.PartyId,
      partyType: PersonalDocument_.PartyType,
    }),
    t.type({
      identityId: Defined,
      id: Defined,
      partyId: Defined,
      partyType: Defined,
    }),
  ]),
  (
    x,
  ): x is t.Branded<
    {
      identityId?: Units_.IdentityId;
      id?: Units_.Uuid;
      partyId?: PersonalDocument_.PartyId;
      partyType?: PersonalDocument_.PartyType;
    } & {
      identityId: Defined;
      id: Defined;
      partyId: Defined;
      partyType: Defined;
    },
    ResponseBrand
  > => true,
  'Response',
);
export interface ResponseBrand {
  readonly Response: unique symbol;
}

export default Response;

// Success
