/*

undefined
Request schema for autocomplete

!!! AUTO GENERATED BY IOTSFJS REFRAIN FROM MANUAL EDITING !!!
See https://www.npmjs.com/package/io-ts-from-json-schema

*/

import * as t from 'io-ts';

import * as Address_2d0a_ from '../../../core/components/address';
import * as ApiCommon_16a4_ from '../../../core/components/api-common';
import * as Units_c404_ from '../../../core/components/units';
import * as UnitsGeo_3e31_ from '../../../core/components/units-geo';

export type Defined = {} | null;
export class DefinedType extends t.Type<Defined> {
  readonly _tag: 'DefinedType' = 'DefinedType';
  constructor() {
    super(
      'defined',
      (u): u is Defined => typeof u !== 'undefined',
      (u, c) => (this.is(u) ? t.success(u) : t.failure(u, c)),
      t.identity,
    );
  }
}
export type DefinedC = {} & DefinedType;
export const Defined: DefinedC = new DefinedType();

export const schemaId =
  'https://schemas.maas.global/maas-backend/autocomplete/autocomplete-query/request.json';

// Request
// The default export. More information at the top.
export type Request = t.Branded<
  {
    identityId?: Units_c404_.IdentityId;
    payload?: {
      name?: Address_2d0a_.PlaceName;
      lat?: UnitsGeo_3e31_.RelaxedLatitude;
      lon?: UnitsGeo_3e31_.RelaxedLongitude;
      providerHint?: string;
      count?: number;
      radius?: UnitsGeo_3e31_.Distance & unknown;
    } & {
      name: Defined;
      lat: Defined;
      lon: Defined;
    };
    headers?: ApiCommon_16a4_.Headers;
  } & Record<string, unknown>,
  RequestBrand
>;
export type RequestC = t.BrandC<
  t.IntersectionC<
    [
      t.PartialC<{
        identityId: typeof Units_c404_.IdentityId;
        payload: t.IntersectionC<
          [
            t.PartialC<{
              name: typeof Address_2d0a_.PlaceName;
              lat: typeof UnitsGeo_3e31_.RelaxedLatitude;
              lon: typeof UnitsGeo_3e31_.RelaxedLongitude;
              providerHint: t.StringC;
              count: t.NumberC;
              radius: t.IntersectionC<[typeof UnitsGeo_3e31_.Distance, t.UnknownC]>;
            }>,
            t.TypeC<{
              name: typeof Defined;
              lat: typeof Defined;
              lon: typeof Defined;
            }>,
          ]
        >;
        headers: typeof ApiCommon_16a4_.Headers;
      }>,
      t.RecordC<t.StringC, t.UnknownC>,
    ]
  >,
  RequestBrand
>;
export const Request: RequestC = t.brand(
  t.intersection([
    t.partial({
      identityId: Units_c404_.IdentityId,
      payload: t.intersection([
        t.partial({
          name: Address_2d0a_.PlaceName,
          lat: UnitsGeo_3e31_.RelaxedLatitude,
          lon: UnitsGeo_3e31_.RelaxedLongitude,
          providerHint: t.string,
          count: t.number,
          radius: t.intersection([UnitsGeo_3e31_.Distance, t.unknown]),
        }),
        t.type({
          name: Defined,
          lat: Defined,
          lon: Defined,
        }),
      ]),
      headers: ApiCommon_16a4_.Headers,
    }),
    t.record(t.string, t.unknown),
  ]),
  (
    x,
  ): x is t.Branded<
    {
      identityId?: Units_c404_.IdentityId;
      payload?: {
        name?: Address_2d0a_.PlaceName;
        lat?: UnitsGeo_3e31_.RelaxedLatitude;
        lon?: UnitsGeo_3e31_.RelaxedLongitude;
        providerHint?: string;
        count?: number;
        radius?: UnitsGeo_3e31_.Distance & unknown;
      } & {
        name: Defined;
        lat: Defined;
        lon: Defined;
      };
      headers?: ApiCommon_16a4_.Headers;
    } & Record<string, unknown>,
    RequestBrand
  > => true,
  'Request',
);
export type RequestBrand = {
  readonly Request: unique symbol;
};

export default Request;

// Success
