/*

undefined
undefined

!!! AUTO GENERATED BY IOTSFJS REFRAIN FROM MANUAL EDITING !!!
See https://www.npmjs.com/package/io-ts-from-json-schema

*/

import * as Response_ from '../../../tsp/stations-retrieve/response';

export const schemaId =
  'http://maasglobal.com/maas-backend/stations/stations-retrieve/response.json';

// Response
// The default export. More information at the top.
export type Response = Response_.Response;
export const Response = Response_.Response;

export default Response;

// Success
