/*

undefined
Response schema for booking-option-create

!!! AUTO GENERATED BY IOTSFJS REFRAIN FROM MANUAL EDITING !!!
See https://www.npmjs.com/package/io-ts-from-json-schema

*/

import * as t from 'io-ts';

export type Defined = {} | null;
export class DefinedType extends t.Type<Defined> {
  readonly _tag: 'DefinedType' = 'DefinedType';
  constructor() {
    super(
      'defined',
      (u): u is Defined => typeof u !== 'undefined',
      (u, c) => (this.is(u) ? t.success(u) : t.failure(u, c)),
      t.identity,
    );
  }
}
export interface DefinedC extends DefinedType {}
export const Defined: DefinedC = new DefinedType();

export const schemaId =
  'http://maasglobal.com/maas-backend/booking-option-create/response.json';

// Response
// The default export. More information at the top.
export type Response = t.Branded<
  | (Array<unknown> & {
      bookings: Defined;
    })
  | (Array<unknown> & {
      failures: Defined;
    }),
  ResponseBrand
>;
export type ResponseC = t.BrandC<
  t.UnionC<
    [
      t.IntersectionC<
        [
          t.UnknownArrayC,
          t.TypeC<{
            bookings: typeof Defined;
          }>,
        ]
      >,
      t.IntersectionC<
        [
          t.UnknownArrayC,
          t.TypeC<{
            failures: typeof Defined;
          }>,
        ]
      >,
    ]
  >,
  ResponseBrand
>;
export const Response: ResponseC = t.brand(
  t.union([
    t.intersection([
      t.UnknownArray,
      t.type({
        bookings: Defined,
      }),
    ]),
    t.intersection([
      t.UnknownArray,
      t.type({
        failures: Defined,
      }),
    ]),
  ]),
  (
    x,
  ): x is t.Branded<
    | (Array<unknown> & {
        bookings: Defined;
      })
    | (Array<unknown> & {
        failures: Defined;
      }),
    ResponseBrand
  > => true,
  'Response',
);
export interface ResponseBrand {
  readonly Response: unique symbol;
}

export default Response;

// Success
