/*

undefined
MaaS payment parameters for completing booking payment

!!! AUTO GENERATED BY IOTSFJS REFRAIN FROM MANUAL EDITING !!!
See https://www.npmjs.com/package/io-ts-from-json-schema

*/

import * as t from 'io-ts';
import * as Units_ from './units';

export const schemaId =
  'https://schemas.maas.global/core/components/payment-parameters.json';

// StripePaymentParameters
// The purpose of this remains a mystery
export type StripePaymentParameters = t.Branded<
  {
    bookingId?: Units_.Uuid;
    clientSecret?: string;
  },
  StripePaymentParametersBrand
>;
export type StripePaymentParametersC = t.BrandC<
  t.PartialC<{
    bookingId: typeof Units_.Uuid;
    clientSecret: t.StringC;
  }>,
  StripePaymentParametersBrand
>;
export const StripePaymentParameters: StripePaymentParametersC = t.brand(
  t.partial({
    bookingId: Units_.Uuid,
    clientSecret: t.string,
  }),
  (
    x,
  ): x is t.Branded<
    {
      bookingId?: Units_.Uuid;
      clientSecret?: string;
    },
    StripePaymentParametersBrand
  > => true,
  'StripePaymentParameters',
);
export interface StripePaymentParametersBrand {
  readonly StripePaymentParameters: unique symbol;
}

// AvainpayPaymentParameters
// The purpose of this remains a mystery
export type AvainpayPaymentParameters = t.Branded<
  | {
      return_code?: string;
      appid?: string;
      sub_appid?: string;
      mch_id?: string;
      sub_mch_id?: string;
      nonce_str?: string;
      result_code?: string;
      prepay_id?: string;
      trade_type?: string;
      code_url?: string;
      sign?: string;
      paySign?: string;
      timeStamp?: string;
    }
  | {
      appId?: string;
      timeStamp?: string;
      nonceStr?: string;
      package?: string;
      signType?: string;
      paySign?: string;
    }
  | {
      return_code?: string;
      appid?: string;
      mch_id?: string;
      sub_mch_id?: string;
      nonce_str?: string;
      result_code?: string;
      prepay_id?: string;
      trade_type?: string;
      code_url?: string;
      sign?: string;
    },
  AvainpayPaymentParametersBrand
>;
export type AvainpayPaymentParametersC = t.BrandC<
  t.UnionC<
    [
      t.PartialC<{
        return_code: t.StringC;
        appid: t.StringC;
        sub_appid: t.StringC;
        mch_id: t.StringC;
        sub_mch_id: t.StringC;
        nonce_str: t.StringC;
        result_code: t.StringC;
        prepay_id: t.StringC;
        trade_type: t.StringC;
        code_url: t.StringC;
        sign: t.StringC;
        paySign: t.StringC;
        timeStamp: t.StringC;
      }>,
      t.PartialC<{
        appId: t.StringC;
        timeStamp: t.StringC;
        nonceStr: t.StringC;
        package: t.StringC;
        signType: t.StringC;
        paySign: t.StringC;
      }>,
      t.PartialC<{
        return_code: t.StringC;
        appid: t.StringC;
        mch_id: t.StringC;
        sub_mch_id: t.StringC;
        nonce_str: t.StringC;
        result_code: t.StringC;
        prepay_id: t.StringC;
        trade_type: t.StringC;
        code_url: t.StringC;
        sign: t.StringC;
      }>,
    ]
  >,
  AvainpayPaymentParametersBrand
>;
export const AvainpayPaymentParameters: AvainpayPaymentParametersC = t.brand(
  t.union([
    t.partial({
      return_code: t.string,
      appid: t.string,
      sub_appid: t.string,
      mch_id: t.string,
      sub_mch_id: t.string,
      nonce_str: t.string,
      result_code: t.string,
      prepay_id: t.string,
      trade_type: t.string,
      code_url: t.string,
      sign: t.string,
      paySign: t.string,
      timeStamp: t.string,
    }),
    t.partial({
      appId: t.string,
      timeStamp: t.string,
      nonceStr: t.string,
      package: t.string,
      signType: t.string,
      paySign: t.string,
    }),
    t.partial({
      return_code: t.string,
      appid: t.string,
      mch_id: t.string,
      sub_mch_id: t.string,
      nonce_str: t.string,
      result_code: t.string,
      prepay_id: t.string,
      trade_type: t.string,
      code_url: t.string,
      sign: t.string,
    }),
  ]),
  (
    x,
  ): x is t.Branded<
    | {
        return_code?: string;
        appid?: string;
        sub_appid?: string;
        mch_id?: string;
        sub_mch_id?: string;
        nonce_str?: string;
        result_code?: string;
        prepay_id?: string;
        trade_type?: string;
        code_url?: string;
        sign?: string;
        paySign?: string;
        timeStamp?: string;
      }
    | {
        appId?: string;
        timeStamp?: string;
        nonceStr?: string;
        package?: string;
        signType?: string;
        paySign?: string;
      }
    | {
        return_code?: string;
        appid?: string;
        mch_id?: string;
        sub_mch_id?: string;
        nonce_str?: string;
        result_code?: string;
        prepay_id?: string;
        trade_type?: string;
        code_url?: string;
        sign?: string;
      },
    AvainpayPaymentParametersBrand
  > => true,
  'AvainpayPaymentParameters',
);
export interface AvainpayPaymentParametersBrand {
  readonly AvainpayPaymentParameters: unique symbol;
}

// PaymentParameters
// The default export. More information at the top.
export type PaymentParameters = t.Branded<unknown, PaymentParametersBrand>;
export type PaymentParametersC = t.BrandC<t.UnknownC, PaymentParametersBrand>;
export const PaymentParameters: PaymentParametersC = t.brand(
  t.unknown,
  (x): x is t.Branded<unknown, PaymentParametersBrand> => true,
  'PaymentParameters',
);
export interface PaymentParametersBrand {
  readonly PaymentParameters: unique symbol;
}

export default PaymentParameters;

// Success
