/*

undefined
MaaS personal document TSP requirements specification

!!! AUTO GENERATED BY IOTSFJS REFRAIN FROM MANUAL EDITING !!!
See https://www.npmjs.com/package/io-ts-from-json-schema

*/

import * as t from 'io-ts';

export const schemaId =
  'https://schemas.maas.global/core/components/personalDocumentRequiredItem.json';

// PersonalDocumentRequiredItem
// The default export. More information at the top.
export type PersonalDocumentRequiredItem = t.Branded<
  {
    type?: 'allOf' | 'anyOf';
    items?: Array<string>;
  } & Record<string, unknown>,
  PersonalDocumentRequiredItemBrand
>;
export type PersonalDocumentRequiredItemC = t.BrandC<
  t.IntersectionC<
    [
      t.PartialC<{
        type: t.UnionC<[t.LiteralC<'allOf'>, t.LiteralC<'anyOf'>]>;
        items: t.ArrayC<t.StringC>;
      }>,
      t.RecordC<t.StringC, t.UnknownC>,
    ]
  >,
  PersonalDocumentRequiredItemBrand
>;
export const PersonalDocumentRequiredItem: PersonalDocumentRequiredItemC = t.brand(
  t.intersection([
    t.partial({
      type: t.union([t.literal('allOf'), t.literal('anyOf')]),
      items: t.array(t.string),
    }),
    t.record(t.string, t.unknown),
  ]),
  (
    x,
  ): x is t.Branded<
    {
      type?: 'allOf' | 'anyOf';
      items?: Array<string>;
    } & Record<string, unknown>,
    PersonalDocumentRequiredItemBrand
  > => true,
  'PersonalDocumentRequiredItem',
);
export interface PersonalDocumentRequiredItemBrand {
  readonly PersonalDocumentRequiredItem: unique symbol;
}

export default PersonalDocumentRequiredItem;

// Success
