/*

undefined
MaaS personal data permissions specification

!!! AUTO GENERATED BY IOTSFJS REFRAIN FROM MANUAL EDITING !!!
See https://www.npmjs.com/package/io-ts-from-json-schema

*/

import * as t from 'io-ts';

export const schemaId =
  'http://maasglobal.com/core/components/personalDataAllowItem.json';

// PersonalDataAllowItem
// The default export. More information at the top.
export type PersonalDataAllowItem = t.Branded<
  {
    type?: 'allOf' | 'anyOf';
    items?: Array<string>;
  },
  PersonalDataAllowItemBrand
>;
export const PersonalDataAllowItem = t.brand(
  t.partial({
    type: t.union([t.literal('allOf'), t.literal('anyOf')]),
    items: t.array(t.string),
  }),
  (
    x,
  ): x is t.Branded<
    {
      type?: 'allOf' | 'anyOf';
      items?: Array<string>;
    },
    PersonalDataAllowItemBrand
  > => true,
  'PersonalDataAllowItem',
);
export interface PersonalDataAllowItemBrand {
  readonly PersonalDataAllowItem: unique symbol;
}

export default PersonalDataAllowItem;

// Success
