/*

undefined
Schema for MODE_BUSISH meta field

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';


export const schemaId = 'http://maasglobal.com/core/modes/MODE_BUSISH.json';

// MODE_BUSISH
// The default export. More information at the top.
export type MODE_BUSISH = t.Branded<{

}, MODE_BUSISHBrand>
export const MODE_BUSISH = t.brand(t.type({

}), (x): x is t.Branded<{

}, MODE_BUSISHBrand> => true, 'MODE_BUSISH')
export interface MODE_BUSISHBrand {
  readonly MODE_BUSISH: unique symbol
}

export default MODE_BUSISH;

// Success
