/*

undefined
Schemas for MODE_CAR meta field

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as CarRental_ from 'maas-schemas-ts/core/components/car-rental';

export const schemaId = 'http://maasglobal.com/core/modes/MODE_CAR.json';

// MODE_CAR
// The default export. More information at the top.
export type MODE_CAR = CarRental_.CarRental;
export const MODE_CAR = CarRental_.CarRental;

export default MODE_CAR;

// Success
