/*

undefined
Options that can be used for available booking options

!!! AUTO GENERATED BY IOTSFJS REFRAIN FROM MANUAL EDITING !!!
See https://www.npmjs.com/package/io-ts-from-json-schema

*/

import * as t from 'io-ts';

import * as Address_2d0a_ from './address';
import * as Common_ffba_ from './common';
import * as TravelMode_5e34_ from './travel-mode';
import * as Units_c404_ from './units';
import * as UnitsGeo_3e31_ from './units-geo';

export const schemaId = 'https://schemas.maas.global/core/components/agencyOptions.json';

// AgencyOptions
// The default export. More information at the top.
export type AgencyOptions = t.Branded<
  {
    mode?: TravelMode_5e34_.TravelMode;
    agencyId?: Common_ffba_.AgencyId;
    startTime?: Units_c404_.Time;
    endTime?: Units_c404_.Time;
    from?: UnitsGeo_3e31_.ShortLocationString;
    to?: UnitsGeo_3e31_.ShortLocationString;
    fromName?: Address_2d0a_.PlaceName;
    fromAddress?: Address_2d0a_.ComponentAddress;
    fromRadius?: UnitsGeo_3e31_.Distance;
    toName?: Address_2d0a_.PlaceName;
    toAddress?: Address_2d0a_.ComponentAddress;
    toRadius?: UnitsGeo_3e31_.Distance;
  },
  AgencyOptionsBrand
>;
export type AgencyOptionsC = t.BrandC<
  t.PartialC<{
    mode: typeof TravelMode_5e34_.TravelMode;
    agencyId: typeof Common_ffba_.AgencyId;
    startTime: typeof Units_c404_.Time;
    endTime: typeof Units_c404_.Time;
    from: typeof UnitsGeo_3e31_.ShortLocationString;
    to: typeof UnitsGeo_3e31_.ShortLocationString;
    fromName: typeof Address_2d0a_.PlaceName;
    fromAddress: typeof Address_2d0a_.ComponentAddress;
    fromRadius: typeof UnitsGeo_3e31_.Distance;
    toName: typeof Address_2d0a_.PlaceName;
    toAddress: typeof Address_2d0a_.ComponentAddress;
    toRadius: typeof UnitsGeo_3e31_.Distance;
  }>,
  AgencyOptionsBrand
>;
export const AgencyOptions: AgencyOptionsC = t.brand(
  t.partial({
    mode: TravelMode_5e34_.TravelMode,
    agencyId: Common_ffba_.AgencyId,
    startTime: Units_c404_.Time,
    endTime: Units_c404_.Time,
    from: UnitsGeo_3e31_.ShortLocationString,
    to: UnitsGeo_3e31_.ShortLocationString,
    fromName: Address_2d0a_.PlaceName,
    fromAddress: Address_2d0a_.ComponentAddress,
    fromRadius: UnitsGeo_3e31_.Distance,
    toName: Address_2d0a_.PlaceName,
    toAddress: Address_2d0a_.ComponentAddress,
    toRadius: UnitsGeo_3e31_.Distance,
  }),
  (
    x,
  ): x is t.Branded<
    {
      mode?: TravelMode_5e34_.TravelMode;
      agencyId?: Common_ffba_.AgencyId;
      startTime?: Units_c404_.Time;
      endTime?: Units_c404_.Time;
      from?: UnitsGeo_3e31_.ShortLocationString;
      to?: UnitsGeo_3e31_.ShortLocationString;
      fromName?: Address_2d0a_.PlaceName;
      fromAddress?: Address_2d0a_.ComponentAddress;
      fromRadius?: UnitsGeo_3e31_.Distance;
      toName?: Address_2d0a_.PlaceName;
      toAddress?: Address_2d0a_.ComponentAddress;
      toRadius?: UnitsGeo_3e31_.Distance;
    },
    AgencyOptionsBrand
  > => true,
  'AgencyOptions',
);
export type AgencyOptionsBrand = {
  readonly AgencyOptions: unique symbol;
};

export default AgencyOptions;

// Success
