/*

undefined
Customer Selection for Configurator v1

!!! AUTO GENERATED BY IOTSFJS REFRAIN FROM MANUAL EDITING !!!
See https://www.npmjs.com/package/io-ts-from-json-schema

*/

import * as t from 'io-ts';

import * as CustomerSelectionCommon_c07e_ from './customerSelectionCommon';

export const schemaId =
  'https://schemas.maas.global/core/components/customerSelectionV1.json';

// CustomerSelectionV1
// The default export. More information at the top.
export type CustomerSelectionV1 = t.Branded<
  {
    seatDirection?: CustomerSelectionCommon_c07e_.ConfigChoiceSelection;
    stations?: CustomerSelectionCommon_c07e_.ConfigChoiceSelection;
    seatPosition?: CustomerSelectionCommon_c07e_.ConfigChoiceSelection;
    seatType?: CustomerSelectionCommon_c07e_.ConfigChoiceSelection;
    seatFeatures?: CustomerSelectionCommon_c07e_.ConfigChoiceSelection;
    outboundSingle?: CustomerSelectionCommon_c07e_.ConfigChoiceSelection;
    inboundSingle?: CustomerSelectionCommon_c07e_.ConfigChoiceSelection;
    openReturn?: CustomerSelectionCommon_c07e_.ConfigChoiceSelection;
    freeReturn?: CustomerSelectionCommon_c07e_.ConfigChoiceSelection;
    ticketCollectionPoint?: CustomerSelectionCommon_c07e_.TextInputSelection;
    scooterCode?: CustomerSelectionCommon_c07e_.TextInputSelection;
  },
  CustomerSelectionV1Brand
>;
export type CustomerSelectionV1C = t.BrandC<
  t.PartialC<{
    seatDirection: typeof CustomerSelectionCommon_c07e_.ConfigChoiceSelection;
    stations: typeof CustomerSelectionCommon_c07e_.ConfigChoiceSelection;
    seatPosition: typeof CustomerSelectionCommon_c07e_.ConfigChoiceSelection;
    seatType: typeof CustomerSelectionCommon_c07e_.ConfigChoiceSelection;
    seatFeatures: typeof CustomerSelectionCommon_c07e_.ConfigChoiceSelection;
    outboundSingle: typeof CustomerSelectionCommon_c07e_.ConfigChoiceSelection;
    inboundSingle: typeof CustomerSelectionCommon_c07e_.ConfigChoiceSelection;
    openReturn: typeof CustomerSelectionCommon_c07e_.ConfigChoiceSelection;
    freeReturn: typeof CustomerSelectionCommon_c07e_.ConfigChoiceSelection;
    ticketCollectionPoint: typeof CustomerSelectionCommon_c07e_.TextInputSelection;
    scooterCode: typeof CustomerSelectionCommon_c07e_.TextInputSelection;
  }>,
  CustomerSelectionV1Brand
>;
export const CustomerSelectionV1: CustomerSelectionV1C = t.brand(
  t.partial({
    seatDirection: CustomerSelectionCommon_c07e_.ConfigChoiceSelection,
    stations: CustomerSelectionCommon_c07e_.ConfigChoiceSelection,
    seatPosition: CustomerSelectionCommon_c07e_.ConfigChoiceSelection,
    seatType: CustomerSelectionCommon_c07e_.ConfigChoiceSelection,
    seatFeatures: CustomerSelectionCommon_c07e_.ConfigChoiceSelection,
    outboundSingle: CustomerSelectionCommon_c07e_.ConfigChoiceSelection,
    inboundSingle: CustomerSelectionCommon_c07e_.ConfigChoiceSelection,
    openReturn: CustomerSelectionCommon_c07e_.ConfigChoiceSelection,
    freeReturn: CustomerSelectionCommon_c07e_.ConfigChoiceSelection,
    ticketCollectionPoint: CustomerSelectionCommon_c07e_.TextInputSelection,
    scooterCode: CustomerSelectionCommon_c07e_.TextInputSelection,
  }),
  (
    x,
  ): x is t.Branded<
    {
      seatDirection?: CustomerSelectionCommon_c07e_.ConfigChoiceSelection;
      stations?: CustomerSelectionCommon_c07e_.ConfigChoiceSelection;
      seatPosition?: CustomerSelectionCommon_c07e_.ConfigChoiceSelection;
      seatType?: CustomerSelectionCommon_c07e_.ConfigChoiceSelection;
      seatFeatures?: CustomerSelectionCommon_c07e_.ConfigChoiceSelection;
      outboundSingle?: CustomerSelectionCommon_c07e_.ConfigChoiceSelection;
      inboundSingle?: CustomerSelectionCommon_c07e_.ConfigChoiceSelection;
      openReturn?: CustomerSelectionCommon_c07e_.ConfigChoiceSelection;
      freeReturn?: CustomerSelectionCommon_c07e_.ConfigChoiceSelection;
      ticketCollectionPoint?: CustomerSelectionCommon_c07e_.TextInputSelection;
      scooterCode?: CustomerSelectionCommon_c07e_.TextInputSelection;
    },
    CustomerSelectionV1Brand
  > => true,
  'CustomerSelectionV1',
);
export type CustomerSelectionV1Brand = {
  readonly CustomerSelectionV1: unique symbol;
};

export default CustomerSelectionV1;

// Success
