/*

undefined
MaaS.fi routes-query response schema

!!! AUTO GENERATED BY IOTSFJS REFRAIN FROM MANUAL EDITING !!!
See https://www.npmjs.com/package/io-ts-from-json-schema

*/

import * as t from 'io-ts';
import * as Plan_ from '../../../core/plan';
import * as Errors_ from '../../../core/components/errors';

export type Defined = {} | null;
export class DefinedType extends t.Type<Defined> {
  readonly _tag: 'DefinedType' = 'DefinedType';
  constructor() {
    super(
      'defined',
      (u): u is Defined => typeof u !== 'undefined',
      (u, c) => (this.is(u) ? t.success(u) : t.failure(u, c)),
      t.identity,
    );
  }
}
export interface DefinedC extends DefinedType {}
export const Defined: DefinedC = new DefinedType();

export const schemaId =
  'http://maasglobal.com/maas-backend/routes/routes-query/response.json';

// Response
// The default export. More information at the top.
export type Response = t.Branded<
  {
    plan?: Plan_.Plan;
    reasons?: Array<Errors_.Reason>;
    debug?: Record<string, unknown>;
  } & {
    plan: Defined;
  },
  ResponseBrand
>;
export type ResponseC = t.BrandC<
  t.IntersectionC<
    [
      t.PartialC<{
        plan: typeof Plan_.Plan;
        reasons: t.ArrayC<typeof Errors_.Reason>;
        debug: t.UnknownRecordC;
      }>,
      t.TypeC<{
        plan: typeof Defined;
      }>,
    ]
  >,
  ResponseBrand
>;
export const Response: ResponseC = t.brand(
  t.intersection([
    t.partial({
      plan: Plan_.Plan,
      reasons: t.array(Errors_.Reason),
      debug: t.UnknownRecord,
    }),
    t.type({
      plan: Defined,
    }),
  ]),
  (
    x,
  ): x is t.Branded<
    {
      plan?: Plan_.Plan;
      reasons?: Array<Errors_.Reason>;
      debug?: Record<string, unknown>;
    } & {
      plan: Defined;
    },
    ResponseBrand
  > => true,
  'Response',
);
export interface ResponseBrand {
  readonly Response: unique symbol;
}

export default Response;

// Success
