/*

undefined
Request schema for subscriptions-intents-update

!!! AUTO GENERATED BY IOTSFJS REFRAIN FROM MANUAL EDITING !!!
See https://www.npmjs.com/package/io-ts-from-json-schema

*/

import * as t from 'io-ts';

import * as ApiCommon_16a4_ from '../../../core/components/api-common';
import * as Units_c404_ from '../../../core/components/units';
import * as SubscriptionIntent_b244_ from '../subscription-intent';

export type Defined = {} | null;
export class DefinedType extends t.Type<Defined> {
  readonly _tag: 'DefinedType' = 'DefinedType';
  constructor() {
    super(
      'defined',
      (u): u is Defined => typeof u !== 'undefined',
      (u, c) => (this.is(u) ? t.success(u) : t.failure(u, c)),
      t.identity,
    );
  }
}
export type DefinedC = {} & DefinedType;
export const Defined: DefinedC = new DefinedType();

export const schemaId =
  'https://schemas.maas.global/maas-backend/subscriptions/subscriptions-intents-update/request.json';

// Request
// The default export. More information at the top.
export type Request = t.Branded<
  {
    identityId?: Units_c404_.IdentityId;
    userId?: Units_c404_.IdentityId;
    subscriptionIntentId?: Units_c404_.Uuid;
    payload?: SubscriptionIntent_b244_.SubscriptionIntentCreate;
    headers?: ApiCommon_16a4_.Headers;
  } & {
    identityId: Defined;
    userId: Defined;
    subscriptionIntentId: Defined;
    payload: Defined;
  },
  RequestBrand
>;
export type RequestC = t.BrandC<
  t.IntersectionC<
    [
      t.PartialC<{
        identityId: typeof Units_c404_.IdentityId;
        userId: typeof Units_c404_.IdentityId;
        subscriptionIntentId: typeof Units_c404_.Uuid;
        payload: typeof SubscriptionIntent_b244_.SubscriptionIntentCreate;
        headers: typeof ApiCommon_16a4_.Headers;
      }>,
      t.TypeC<{
        identityId: typeof Defined;
        userId: typeof Defined;
        subscriptionIntentId: typeof Defined;
        payload: typeof Defined;
      }>,
    ]
  >,
  RequestBrand
>;
export const Request: RequestC = t.brand(
  t.intersection([
    t.partial({
      identityId: Units_c404_.IdentityId,
      userId: Units_c404_.IdentityId,
      subscriptionIntentId: Units_c404_.Uuid,
      payload: SubscriptionIntent_b244_.SubscriptionIntentCreate,
      headers: ApiCommon_16a4_.Headers,
    }),
    t.type({
      identityId: Defined,
      userId: Defined,
      subscriptionIntentId: Defined,
      payload: Defined,
    }),
  ]),
  (
    x,
  ): x is t.Branded<
    {
      identityId?: Units_c404_.IdentityId;
      userId?: Units_c404_.IdentityId;
      subscriptionIntentId?: Units_c404_.Uuid;
      payload?: SubscriptionIntent_b244_.SubscriptionIntentCreate;
      headers?: ApiCommon_16a4_.Headers;
    } & {
      identityId: Defined;
      userId: Defined;
      subscriptionIntentId: Defined;
      payload: Defined;
    },
    RequestBrand
  > => true,
  'Request',
);
export type RequestBrand = {
  readonly Request: unique symbol;
};

export default Request;

// Success
