/*

undefined
Request schema for webhooks-bookings-create

!!! AUTO GENERATED BY IOTSFJS REFRAIN FROM MANUAL EDITING !!!
See https://www.npmjs.com/package/io-ts-from-json-schema

*/

import * as t from 'io-ts';
import * as Units_ from '../../../core/components/units';
import * as I18n_ from '../../../core/components/i18n';
import * as Booking_ from '../../../core/booking';
import * as BookingMeta_ from '../../../core/booking-meta';
import * as CustomerSelection_ from '../../../core/components/customerSelection';
import * as ApiCommon_ from '../../../core/components/api-common';

export type Defined = {} | null;
export class DefinedType extends t.Type<Defined> {
  readonly _tag: 'DefinedType' = 'DefinedType';
  constructor() {
    super(
      'defined',
      (u): u is Defined => typeof u !== 'undefined',
      (u, c) => (this.is(u) ? t.success(u) : t.failure(u, c)),
      t.identity,
    );
  }
}
export interface DefinedC extends DefinedType {}
export const Defined: DefinedC = new DefinedType();

export const schemaId =
  'https://schemas.maas.global/maas-backend/webhooks/webhooks-bookings-create/request.json';

// Request
// The default export. More information at the top.
export type Request = t.Branded<
  {
    payload?: {
      identityId?: Units_.IdentityId;
      locale?: I18n_.Locale;
      option?: {
        cost?: Booking_.Cost;
        leg?: Booking_.Leg;
        meta?: BookingMeta_.BookingMeta;
        terms?: Booking_.Terms;
        tspProduct?: {
          id?: string;
        };
        configurator?: Booking_.Configurator;
      } & (
        | {
            leg: Defined;
            terms: Defined;
            cost: Defined;
            meta: Defined;
          }
        | {
            leg: Defined;
            terms: Defined;
            cost: Defined;
            meta: Defined;
            configurator: Defined;
          }
      );
      customerSelection?: CustomerSelection_.CustomerSelection;
    } & {
      option: Defined;
      identityId: Defined;
      locale: Defined;
    };
    headers?: ApiCommon_.Headers;
  } & {
    payload: Defined;
  },
  RequestBrand
>;
export type RequestC = t.BrandC<
  t.IntersectionC<
    [
      t.PartialC<{
        payload: t.IntersectionC<
          [
            t.PartialC<{
              identityId: typeof Units_.IdentityId;
              locale: typeof I18n_.Locale;
              option: t.IntersectionC<
                [
                  t.PartialC<{
                    cost: typeof Booking_.Cost;
                    leg: typeof Booking_.Leg;
                    meta: typeof BookingMeta_.BookingMeta;
                    terms: typeof Booking_.Terms;
                    tspProduct: t.PartialC<{
                      id: t.StringC;
                    }>;
                    configurator: typeof Booking_.Configurator;
                  }>,
                  t.UnionC<
                    [
                      t.TypeC<{
                        leg: typeof Defined;
                        terms: typeof Defined;
                        cost: typeof Defined;
                        meta: typeof Defined;
                      }>,
                      t.TypeC<{
                        leg: typeof Defined;
                        terms: typeof Defined;
                        cost: typeof Defined;
                        meta: typeof Defined;
                        configurator: typeof Defined;
                      }>,
                    ]
                  >,
                ]
              >;
              customerSelection: typeof CustomerSelection_.CustomerSelection;
            }>,
            t.TypeC<{
              option: typeof Defined;
              identityId: typeof Defined;
              locale: typeof Defined;
            }>,
          ]
        >;
        headers: typeof ApiCommon_.Headers;
      }>,
      t.TypeC<{
        payload: typeof Defined;
      }>,
    ]
  >,
  RequestBrand
>;
export const Request: RequestC = t.brand(
  t.intersection([
    t.partial({
      payload: t.intersection([
        t.partial({
          identityId: Units_.IdentityId,
          locale: I18n_.Locale,
          option: t.intersection([
            t.partial({
              cost: Booking_.Cost,
              leg: Booking_.Leg,
              meta: BookingMeta_.BookingMeta,
              terms: Booking_.Terms,
              tspProduct: t.partial({
                id: t.string,
              }),
              configurator: Booking_.Configurator,
            }),
            t.union([
              t.type({
                leg: Defined,
                terms: Defined,
                cost: Defined,
                meta: Defined,
              }),
              t.type({
                leg: Defined,
                terms: Defined,
                cost: Defined,
                meta: Defined,
                configurator: Defined,
              }),
            ]),
          ]),
          customerSelection: CustomerSelection_.CustomerSelection,
        }),
        t.type({
          option: Defined,
          identityId: Defined,
          locale: Defined,
        }),
      ]),
      headers: ApiCommon_.Headers,
    }),
    t.type({
      payload: Defined,
    }),
  ]),
  (
    x,
  ): x is t.Branded<
    {
      payload?: {
        identityId?: Units_.IdentityId;
        locale?: I18n_.Locale;
        option?: {
          cost?: Booking_.Cost;
          leg?: Booking_.Leg;
          meta?: BookingMeta_.BookingMeta;
          terms?: Booking_.Terms;
          tspProduct?: {
            id?: string;
          };
          configurator?: Booking_.Configurator;
        } & (
          | {
              leg: Defined;
              terms: Defined;
              cost: Defined;
              meta: Defined;
            }
          | {
              leg: Defined;
              terms: Defined;
              cost: Defined;
              meta: Defined;
              configurator: Defined;
            }
        );
        customerSelection?: CustomerSelection_.CustomerSelection;
      } & {
        option: Defined;
        identityId: Defined;
        locale: Defined;
      };
      headers?: ApiCommon_.Headers;
    } & {
      payload: Defined;
    },
    RequestBrand
  > => true,
  'Request',
);
export interface RequestBrand {
  readonly Request: unique symbol;
}

export default Request;

// Success
