/*

undefined
undefined

!!! AUTO GENERATED BY IOTSFJS REFRAIN FROM MANUAL EDITING !!!
See https://www.npmjs.com/package/io-ts-from-json-schema

*/

import * as t from 'io-ts';

import * as BikeStation_4888_ from '../components/bike-station';
import * as Vehicle_52ac_ from '../components/vehicle';

export type Defined = {} | null;
export class DefinedType extends t.Type<Defined> {
  readonly _tag: 'DefinedType' = 'DefinedType';
  constructor() {
    super(
      'defined',
      (u): u is Defined => typeof u !== 'undefined',
      (u, c) => (this.is(u) ? t.success(u) : t.failure(u, c)),
      t.identity,
    );
  }
}
export type DefinedC = {} & DefinedType;
export const Defined: DefinedC = new DefinedType();

export const schemaId = 'https://schemas.maas.global/core/modes/MODE_BICYCLE.json';

// MODE_BICYCLE
// The default export. More information at the top.
export type MODE_BICYCLE = t.Branded<
  {
    pickupStation?: BikeStation_4888_.BikeStation;
    returnStation?: BikeStation_4888_.BikeStation;
    pickupStationId?: string;
    returnStationId?: string;
    bike?: ({
      id?: Vehicle_52ac_.VehicleId;
      type?: string;
    } & Record<string, unknown>) & {
      id: Defined;
    };
  } & Record<string, unknown>,
  MODE_BICYCLEBrand
>;
export type MODE_BICYCLEC = t.BrandC<
  t.IntersectionC<
    [
      t.PartialC<{
        pickupStation: typeof BikeStation_4888_.BikeStation;
        returnStation: typeof BikeStation_4888_.BikeStation;
        pickupStationId: t.StringC;
        returnStationId: t.StringC;
        bike: t.IntersectionC<
          [
            t.IntersectionC<
              [
                t.PartialC<{
                  id: typeof Vehicle_52ac_.VehicleId;
                  type: t.StringC;
                }>,
                t.RecordC<t.StringC, t.UnknownC>,
              ]
            >,
            t.TypeC<{
              id: typeof Defined;
            }>,
          ]
        >;
      }>,
      t.RecordC<t.StringC, t.UnknownC>,
    ]
  >,
  MODE_BICYCLEBrand
>;
export const MODE_BICYCLE: MODE_BICYCLEC = t.brand(
  t.intersection([
    t.partial({
      pickupStation: BikeStation_4888_.BikeStation,
      returnStation: BikeStation_4888_.BikeStation,
      pickupStationId: t.string,
      returnStationId: t.string,
      bike: t.intersection([
        t.intersection([
          t.partial({
            id: Vehicle_52ac_.VehicleId,
            type: t.string,
          }),
          t.record(t.string, t.unknown),
        ]),
        t.type({
          id: Defined,
        }),
      ]),
    }),
    t.record(t.string, t.unknown),
  ]),
  (
    x,
  ): x is t.Branded<
    {
      pickupStation?: BikeStation_4888_.BikeStation;
      returnStation?: BikeStation_4888_.BikeStation;
      pickupStationId?: string;
      returnStationId?: string;
      bike?: ({
        id?: Vehicle_52ac_.VehicleId;
        type?: string;
      } & Record<string, unknown>) & {
        id: Defined;
      };
    } & Record<string, unknown>,
    MODE_BICYCLEBrand
  > => true,
  'MODE_BICYCLE',
);
export type MODE_BICYCLEBrand = {
  readonly MODE_BICYCLE: unique symbol;
};

export default MODE_BICYCLE;

// Success
