/*

undefined
undefined

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as Response_ from 'maas-schemas-ts/tsp/stations-list/response';


export const schemaId = 'http://maasglobal.com/maas-backend/stations/stations-list/response.json';

// Response
// The default export. More information at the top.
export type Response = Response_.Response
export const Response = Response_.Response

export default Response;

// Success
