/*

undefined
Request schema for subscriptions-intents-update-state

!!! AUTO GENERATED BY IOTSFJS REFRAIN FROM MANUAL EDITING !!!
See https://www.npmjs.com/package/io-ts-from-json-schema

*/

import * as t from 'io-ts';

import * as ApiCommon_ from '../../../core/components/api-common';
import * as State_ from '../../../core/components/state';
import * as Units_ from '../../../core/components/units';

export type Defined = {} | null;
export class DefinedType extends t.Type<Defined> {
  readonly _tag: 'DefinedType' = 'DefinedType';
  constructor() {
    super(
      'defined',
      (u): u is Defined => typeof u !== 'undefined',
      (u, c) => (this.is(u) ? t.success(u) : t.failure(u, c)),
      t.identity,
    );
  }
}
export type DefinedC = {} & DefinedType;
export const Defined: DefinedC = new DefinedType();

export const schemaId =
  'https://schemas.maas.global/maas-backend/subscriptions/subscriptions-intents-update-state/request.json';

// Request
// The default export. More information at the top.
export type Request = t.Branded<
  {
    identityId?: Units_.IdentityId;
    userId?: Units_.IdentityId;
    subscriptionIntentId?: Units_.Uuid;
    payload?: {
      state?: State_.SubscriptionIntentState;
    } & Record<string, unknown>;
    headers?: ApiCommon_.Headers;
  } & {
    identityId: Defined;
    userId: Defined;
    subscriptionIntentId: Defined;
    payload: Defined;
  },
  RequestBrand
>;
export type RequestC = t.BrandC<
  t.IntersectionC<
    [
      t.PartialC<{
        identityId: typeof Units_.IdentityId;
        userId: typeof Units_.IdentityId;
        subscriptionIntentId: typeof Units_.Uuid;
        payload: t.IntersectionC<
          [
            t.PartialC<{
              state: typeof State_.SubscriptionIntentState;
            }>,
            t.RecordC<t.StringC, t.UnknownC>,
          ]
        >;
        headers: typeof ApiCommon_.Headers;
      }>,
      t.TypeC<{
        identityId: typeof Defined;
        userId: typeof Defined;
        subscriptionIntentId: typeof Defined;
        payload: typeof Defined;
      }>,
    ]
  >,
  RequestBrand
>;
export const Request: RequestC = t.brand(
  t.intersection([
    t.partial({
      identityId: Units_.IdentityId,
      userId: Units_.IdentityId,
      subscriptionIntentId: Units_.Uuid,
      payload: t.intersection([
        t.partial({
          state: State_.SubscriptionIntentState,
        }),
        t.record(t.string, t.unknown),
      ]),
      headers: ApiCommon_.Headers,
    }),
    t.type({
      identityId: Defined,
      userId: Defined,
      subscriptionIntentId: Defined,
      payload: Defined,
    }),
  ]),
  (
    x,
  ): x is t.Branded<
    {
      identityId?: Units_.IdentityId;
      userId?: Units_.IdentityId;
      subscriptionIntentId?: Units_.Uuid;
      payload?: {
        state?: State_.SubscriptionIntentState;
      } & Record<string, unknown>;
      headers?: ApiCommon_.Headers;
    } & {
      identityId: Defined;
      userId: Defined;
      subscriptionIntentId: Defined;
      payload: Defined;
    },
    RequestBrand
  > => true,
  'Request',
);
export type RequestBrand = {
  readonly Request: unique symbol;
};

export default Request;

// Success
