/*

undefined
Initiate customer KYC process

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';
import * as Units_ from 'maas-schemas-ts/core/components/units';
import * as PersonalDocument_ from 'maas-schemas-ts/core/personal-document';
import * as UnitsGeo_ from 'maas-schemas-ts/core/components/units-geo';
import * as ApiCommon_ from 'maas-schemas-ts/core/components/api-common';


type Defined =
  (
  | Record<string, unknown>
  | Array<unknown>
  | string
  | boolean
  | number
  | null
  )
const Defined = t.union([
  t.UnknownRecord,
  t.UnknownArray,
  t.string,
  t.boolean,
  t.number,
  t.null
])


export const schemaId = 'http://maasglobal.com/maas-backend/customers/personal-documents/initiate/request.json';

// Request
// The default export. More information at the top.
export type Request = t.Branded<
  (
  & {
  identityId?: Units_.IdentityId,
  payload?:
    (
    & {
    type?: PersonalDocument_.DocumentType,
    location?: UnitsGeo_.ShortLocationString
  }
    & {
    type: Defined,
    location: Defined
  }
    ),
  headers?: ApiCommon_.Headers
}
  & {
  identityId: Defined,
  payload: Defined,
  headers: Defined
}
  ), RequestBrand>
export const Request = t.brand(t.intersection([
  t.partial({
    identityId: Units_.IdentityId,
    payload: t.intersection([
      t.partial({
        type: PersonalDocument_.DocumentType,
        location: UnitsGeo_.ShortLocationString
      }),
      t.type({
        type: Defined,
        location: Defined
      })
    ]),
    headers: ApiCommon_.Headers
  }),
  t.type({
    identityId: Defined,
    payload: Defined,
    headers: Defined
  })
]), (x): x is t.Branded<
  (
  & {
  identityId?: Units_.IdentityId,
  payload?:
    (
    & {
    type?: PersonalDocument_.DocumentType,
    location?: UnitsGeo_.ShortLocationString
  }
    & {
    type: Defined,
    location: Defined
  }
    ),
  headers?: ApiCommon_.Headers
}
  & {
  identityId: Defined,
  payload: Defined,
  headers: Defined
}
  ), RequestBrand> => true, 'Request')
export interface RequestBrand {
  readonly Request: unique symbol
}

export default Request;

// Success
