/*

undefined
Initiate customer KYC process

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as KycService_ from 'maas-schemas-ts/core/kyc-service';


export const schemaId = 'http://maasglobal.com/maas-backend/customers/personal-documents/initiate/response.json';

// Response
// The default export. More information at the top.
export type Response = KycService_.KycService
export const Response = KycService_.KycService

export default Response;

// Success
