/*

undefined
MaaS Invoice Units schema

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';

export const schemaId = 'http://maasglobal.com/maas-backend/invoices/invoiceUnits.json';
// InvoiceId
// The purpose of this remains a mystery
export type InvoiceId = t.Branded<string, InvoiceIdBrand>;
export const InvoiceId = t.brand(
  t.string,
  (x): x is t.Branded<string, InvoiceIdBrand> => typeof x !== 'string' || x.length >= 2,
  'InvoiceId',
);
export interface InvoiceIdBrand {
  readonly InvoiceId: unique symbol;
}
// InvoiceLineItemId
// The purpose of this remains a mystery
export type InvoiceLineItemId = t.Branded<string, InvoiceLineItemIdBrand>;
export const InvoiceLineItemId = t.brand(
  t.string,
  (x): x is t.Branded<string, InvoiceLineItemIdBrand> =>
    typeof x !== 'string' || x.length >= 2,
  'InvoiceLineItemId',
);
export interface InvoiceLineItemIdBrand {
  readonly InvoiceLineItemId: unique symbol;
}
// Default
// The default export. More information at the top.
export type Default = t.Branded<unknown, DefaultBrand>;
export const Default = t.brand(
  t.unknown,
  (x): x is t.Branded<unknown, DefaultBrand> => true,
  'Default',
);
export interface DefaultBrand {
  readonly Default: unique symbol;
}

export default Default;

// Success
